### ISSUE TITLE
Exception trying to clean html mail

### ISSUE THREAD

**Issue by mortenn** [lukeschafer/HtmlCleanser#3]
Hi, I just installed the nuget and when I try to clean an email, I get this exception;

```
Encountered an exception 'System.FormatException: Invalid character at position 2.
==================== Begin stack trace ====================
   at Fizzler.Tokener.<Tokenize>d__0.MoveNext()
   at Fizzler.Reader`1.RealRead()
   at Fizzler.Reader`1.Read()
   at Fizzler.Parser.TryRead(Either`2 spec)
   at Fizzler.Parser.TryRead(Either`2[] specs)
   at Fizzler.Parser.TryNamespacePrefix()
   at Fizzler.Parser.TypeSelectorOrUniversal()
   at Fizzler.Parser.SimpleSelectorSequence()
   at Fizzler.Parser.Selector()
   at Fizzler.Parser.SelectorGroup()
   at Fizzler.Parser.Parse[TGenerator,T](IEnumerable`1 tokens, TGenerator generator, Func`2 resultor)
   at Fizzler.Systems.HtmlAgilityPack.HtmlNodeSelection.Compile(String selector)
   at Fizzler.Systems.HtmlAgilityPack.HtmlNodeSelection.QuerySelectorAll(HtmlNode node, String selector, Func`2 compiler)
   at HtmlCleanser.Rules.StylesShouldBeInline.Perform(HtmlDocument doc)
   at HtmlCleanser.HtmlCleanser.Perform(String htmlInput, IEnumerable`1 rulesToUse, Type[] rulesToIgnore, Boolean justReturnTheBodyContents)
   at HtmlCleanser.HtmlCleanser.CleanseFull(String htmlInput, Boolean justReturnTheBodyContents)
   at MailParser.Framework.ImportableEmail.RemoveCrud(MessageBody emailMessage)
```

**Comment by mortenn** [comment]
Ignoring the `StylesShouldBeInline` rule made the exception go away.

**Comment by lukeschafer** [comment]
Thanks. Do you have a sample of HTML that causes this?

**Comment by mortenn** [comment]
I can't release the email that caused the exception, but I will look into making a sample that causes the same error.

**Comment by mortenn** [comment]
I was able to get a sample. deleting the content of the body tag made the error still get thrown.
https://ghostbin.com/paste/kvg8a
I think I know why, will do some additional tests and come back with a minified example should I be right.

**Comment by mortenn** [comment]
My guess was wrong, but managed to minimize it all the same.
`<!--[if !mso]><style>v\:* {}</style><![endif]-->` will make it die. the `<!--[if` is irrelevant, but I left it in.

**Comment by mortenn** [comment]
hmm, on a closer look, the last comments html fragment makes a different error. disregard that comment

**Comment by mortenn** [comment]
`<html><head><!--[if !mso]><style>v\:* {}</style><![endif]--></head></html>` gives the invalid character exception. removing the `\` makes that error go away, giving a `Unexpected token {Char} where {Ident} was expected.` instead.

**Comment by mortenn** [comment]
The second exception is due to the `v:*` - another case of xml namespaced tags, this time in css, I suspect.
